In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
import os

In [3]:
# Load your trained model
model = tf.keras.models.load_model("model_file.h5")

# Path to your test dataset
test_dir = r"C:\Users\kezin\Downloads\archive\test"  # Update this to your test image folder

# Image parameters (should match your model's input size)
IMG_SIZE = (48, 48)  # Update if different
BATCH_SIZE = 32  # Adjust batch size as needed

# Load test images using ImageDataGenerator
test_datagen = ImageDataGenerator(rescale=1./255)  # Normalize images
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',  # Ensures labels are one-hot encoded
    color_mode='grayscale',  # Force grayscale images (fix for input shape mismatch)
    shuffle=False  
)

# Get true labels
y_true = test_generator.classes
class_labels = list(test_generator.class_indices.keys())  # Get class names

# Predict on test data
y_pred_probs = model.predict(test_generator)
y_pred = np.argmax(y_pred_probs, axis=1)  # Convert probabilities to class labels

# Calculate metrics
accuracy = accuracy_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred, average="weighted")
conf_matrix = confusion_matrix(y_true, y_pred)
report = classification_report(y_true, y_pred, target_names=class_labels)

# Print results
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(report)


Found 7178 images belonging to 7 classes.


c:\Users\kezin\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


225/225 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step
Accuracy: 0.5687
F1 Score: 0.5626
Confusion Matrix:
[[ 430    1  107   79  140  165   36]
 [  53   16   11    5    7   17    2]
 [ 126    1  319   59  154  244  121]
 [  50    0   51 1467  107   60   39]
 [  77    1  107  108  686  217   37]
 [ 139    0  153   93  245  585   32]
 [  29    1  105   62   39   16  579]]

Classification Report:
              precision    recall  f1-score   support

       angry       0.48      0.45      0.46       958
     disgust       0.80      0.14      0.24       111
        fear       0.37      0.31      0.34      1024
       happy       0.78      0.83      0.80      1774
     neutral       0.50      0.56      0.53      1233
         sad       0.45      0.47      0.46      1247
    surprise       0.68      0.70      0.69       831

    accuracy                           0.57      7178
   macro avg       0.58      0.49      0.50      7178
weighted avg       0.57      0.57      0.56      7178

